name: CI/CD Pipeline 

on:
  push:
    branches:
    - main

jobs: 
  deploy:
    runs-on: windows-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Application
        run : | 
          py application.py
