name: Sync Files to Local Machine

on:
  push:
    branches:
      - main

jobs:
  sync_files:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sync Files
        run: |
          robocopy ${{ github.workspace }} "C:\Users\matsvei_t\Desktop\всякое\python\Flask_app" /MIR /LOG:"$env:TEMP\robocopy-log.txt"
      
      - name: Display Robocopy Log
        run: |
          Get-Content "$env:TEMP\robocopy-log.txt"
