name: CI/CD Pipeline 

on:
  push:
    branches:
    - main

jobs: 
  deploy:
    runs-on: windows-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version : 3.8

      - name: Activate Virtual Environment
        run: |
          py -m venv venv
          .\venv\Scripts\Activate
      
      - name: Install Dependencies
        run: |
          py -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Flask Application
        run : | 
          py application.py
