name: CI/CD Pipeline 

on:
  push:
    branches:
    - main

jobs: 
  deploy:
    runs-on: windows-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run : | 
          py -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Deploy Application
        run : |
          py -m pip install --upgrade pip
          pip install -r requirements.txt 
          py application.py
